version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysql-short-url
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: short-url
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always


  redis:
    image: redis:7.0.11
    container_name: redis-short-url
    ports:
      - "6380:6379"
    restart: always

volumes:
  dbdata: