version: "3"

services:
  backend:
    image: ernesto27/short-url:v0.0.4
    container_name: backend-short-url
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    command: ./myapp
    ports:
      - "8080:8080"
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql-short-url
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: short-url
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  nginx:
    image: nginx
    container_name: nginx-short-url
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  dbdata: