CREATE DATABASE `short-url` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `short-url`;

CREATE TABLE short_url (
  id INT NOT NULL AUTO_INCREMENT,
  hash VARCHAR(7) NOT NULL,
  url VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (hash)
);
