name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: short-url
          MYSQL_ROOT_PASSWORD: 1111
        ports:
          # Opens port 3306 on service container and host
          # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Static analysis
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go vet ./...
          staticcheck ./...

      - name: Test
        run: echo "${{ secrets.ENV }}" > .env && cat .env && go test -v ./...
